#!/bin/sh

set -ev

SRCDIR="$(pwd)"

cd "$AUTOPKGTEST_TMP"

cmake -DCMake_TEST_EXTERNAL_CMAKE=/usr/bin "$SRCDIR"
make VERBOSE=1
unset http_proxy
unset https_proxy
unset no_proxy
CTEST_OUTPUT_ON_FAILURE=1 ctest -E '(CTestTestUpload|BootstrapTest)'
